"use client";

import { LoadingCard, SectionHead, TextField } from "../fields";
import { t01PortraitSubtitleMaxCharacters } from "@/contracts/poster";
import type { RenderTargetId } from "@/contracts/brand";
import { renderTargetOptions } from "../activity-studio-model";
import type { ActivityJob, CopyReview, FormState } from "../types";

export function StepTwo({ form, review, job, onChange, onBack, onConfirm, pending, renderTargets, fixtureMode }: { form: FormState; review?: CopyReview; job?: ActivityJob; onChange: (value: CopyReview) => void; onBack: () => void; onConfirm: () => void; pending: boolean; renderTargets: RenderTargetId[]; fixtureMode: boolean }) {
  const document = job?.copyDraft?.document;
  if (!review || !document) return <LoadingCard title="正在生成文案" detail={job?.currentStep ?? "请稍候…"} />;
  return <section className="ead-section"><SectionHead index="02" title="确认文案" hint="必填事实只读；可选叙述可继续微调" />{fixtureMode && <div className="ead-target-summary"><b>本次输出物料</b><span>{renderTargetOptions.filter((option) => renderTargets.includes(option.id)).map((option) => <em key={option.id}>{option.name} · {option.size}</em>)}</span></div>}<div className="ead-copy-note">副标题会直接进入 T01 竖版海报，最多 {t01PortraitSubtitleMaxCharacters} 个字；AI 已按该容量生成，仍可编辑。</div><div className="ead-readonly-facts"><span><b>主题</b>{form.activityName}</span><span><b>时间</b>{[form.session, ...(form.secondSession ? [form.secondSession] : [])].map((session) => `${session.date} · ${session.time}`).join(" / ")}</span><span><b>地点</b>{[form.session, ...(form.secondSession ? [form.secondSession] : [])].map((session) => session.location).join(" / ")}</span><span><b>对象</b>{form.audience}</span></div><div className="ead-compare"><div><small>原始输入</small><p>{form.supplement || "未填写"}</p><p>{form.rules || "未填写"}</p><p>{form.prize || "未填写"}</p></div><div><small>AI 优化后，可编辑</small><TextField label={`副标题（最多 ${t01PortraitSubtitleMaxCharacters} 字）`} value={review.subtitle} maxLength={t01PortraitSubtitleMaxCharacters} onChange={(value) => onChange({ ...review, subtitle: value })} /><TextField label="补充说明（不展示在当前竖版）" value={review.summary} onChange={(value) => onChange({ ...review, summary: value })} /><TextField label="活动规则" value={review.rules} onChange={(value) => onChange({ ...review, rules: value })} /><TextField label="奖品" value={review.prize} onChange={(value) => onChange({ ...review, prize: value })} /></div></div><p className="ead-unprojected">截止时间与联系人用于长图，竖版不展示；奖品保存到任务，当前暂无独立展示槽位。</p><div className="ead-stage-actions"><button type="button" className="ead-secondary" onClick={onBack} disabled={pending}>返回修改</button><button type="button" className="ead-primary" onClick={onConfirm} disabled={pending}>{pending ? "正在确认…" : "确认文案，进入主视觉 →"}</button></div></section>;
}
