"use client";

import { LoadingCard, SectionHead, TextField } from "../fields";
import { t01PortraitSubtitleMaxCharacters, t01PortraitSubtitleRecommendedCharacters } from "@/contracts/poster";
import type { ActivityJob, CopyReview, FormState } from "../types";

export function StepTwo({ form, review, job, onChange, onBack, onConfirm, pending }: { form: FormState; review?: CopyReview; job?: ActivityJob; onChange: (value: CopyReview) => void; onBack: () => void; onConfirm: () => void; pending: boolean }) {
  const document = job?.copyDraft?.document;
  if (!review || !document) return <LoadingCard title="正在生成文案" detail={job?.currentStep ?? "请稍候…"} />;
  return <section className="ead-section"><SectionHead index="02" title="确认文案" hint="必填事实只读；可选叙述可继续微调" /><div className="ead-copy-note">副标题宽度 952px、高度自适应，建议 {t01PortraitSubtitleRecommendedCharacters} 个字以内；最多 {t01PortraitSubtitleMaxCharacters} 个字，最终按实际边界校验。</div><div className="ead-readonly-facts"><span><b>主题</b>{form.activityName}</span><span><b>时间</b>{`${form.session.date} · ${form.session.time}`}</span><span><b>地点</b>{form.session.location}</span><span><b>对象</b>{form.audience}</span></div><div className="ead-compare"><div><small>原始输入</small><p>{form.supplement || "未填写"}</p><p>{form.rules || "未填写"}</p><p>{form.prize || "未填写"}</p></div><div><small>AI 优化后，可编辑</small><TextField label={`副标题（建议 ${t01PortraitSubtitleRecommendedCharacters} 字以内，最多 ${t01PortraitSubtitleMaxCharacters} 字）`} value={review.subtitle} maxLength={t01PortraitSubtitleMaxCharacters} onChange={(value) => onChange({ ...review, subtitle: value })} /><TextField label="补充说明（不展示在当前竖版）" value={review.summary} onChange={(value) => onChange({ ...review, summary: value })} /><TextField label="活动规则" value={review.rules} onChange={(value) => onChange({ ...review, rules: value })} /><TextField label="奖品" value={review.prize} onChange={(value) => onChange({ ...review, prize: value })} /></div></div><p className="ead-unprojected">截止时间与联系人用于长图，竖版不展示；奖品保存到任务，当前暂无独立展示槽位。</p><div className="ead-stage-actions"><button type="button" className="ead-secondary" onClick={onBack} disabled={pending}>返回修改</button><button type="button" className="ead-primary" onClick={onConfirm} disabled={pending}>{pending ? "正在确认…" : "确认文案，进入主视觉 →"}</button></div></section>;
}
