"use client";
import type { FormEvent } from "react";
import { t01PortraitSubtitleRecommendedCharacters } from "@/contracts/poster";
import { Field, SectionHead, TextField } from "../fields";
import type { FormState, QrMode, SessionState } from "../types";
import type { RenderTargetId } from "@/contracts/brand";

const targets: Array<[RenderTargetId, string, string]> = [["portrait_1080x1920", "竖版", "1080 × 1920"], ["landscape_1920x1080", "横版", "1920 × 1080"], ["banner_2227x950", "Banner", "2227 × 950"], ["longform_1080xAuto", "长图", "1080 × 自动"]];
type Props = { form: FormState; qrMode: QrMode; qrUploadPending: boolean; aiReady: boolean; aiCandidate?: { slogan: string; subtitle: string }; onToggleRenderTarget: (target: RenderTargetId) => void; onField: <K extends keyof FormState>(key: K, value: FormState[K]) => void; onQrUrl: (value: string) => void; onSession: (key: keyof SessionState, value: string) => void; onQrMode: (mode: QrMode) => void; onQrUpload: (file?: File) => void; onClearQrAsset: () => void; onAssist: () => void; onSubmit: (event: FormEvent) => void; pending: boolean };

export function StepOne({ form, qrMode, qrUploadPending, aiReady, aiCandidate, onToggleRenderTarget, onField, onQrUrl, onSession, onQrMode, onQrUpload, onClearQrAsset, onAssist, onSubmit, pending }: Props) {
  return <form onSubmit={onSubmit}><section className="ead-section"><SectionHead index="01" title="填写海报信息" />
    <div className="ead-template-picker"><b>选择海报尺寸</b><small>可选择多种尺寸，右侧可切换查看。</small><div>{targets.map(([target, name, size]) => <button type="button" key={target} className={form.renderTargets.includes(target) ? "is-selected" : ""} onClick={() => onToggleRenderTarget(target)}><span>{form.renderTargets.includes(target) ? "✓" : "＋"}</span><strong>{name}</strong><small>{size}</small></button>)}</div></div>
    <div className="ead-grid"><Field className="ead-span-2" label="一级大标题" required multiline value={form.activityName} onChange={(value) => onField("activityName", value)} /><Field className="ead-span-2" label="宣言标题" required value={form.slogan} maxLength={40} hint="格式：九号员工活动名称 / ENGLISH；可手填或由 AI 生成" onChange={(value) => onField("slogan", value)} /><Field className="ead-span-2" label="副标题" required value={form.subtitle} maxLength={40} hint={`建议 ${t01PortraitSubtitleRecommendedCharacters} 字以内；可手填或由 AI 生成`} onChange={(value) => onField("subtitle", value)} /></div>
    <div className="ead-copy-actions"><button type="button" className="ead-secondary" onClick={onAssist} disabled={pending}>{pending ? "正在准备建议…" : aiReady ? "使用文案建议" : "获取文案建议"}</button><small>{aiReady ? "确认使用后，建议会同步到输入框和预览。" : "文案建议不会改动活动主题或活动信息。"}</small></div>
    {aiReady && aiCandidate && <div className="ead-ai-candidate"><b>文案建议</b><p><span>宣言标题</span>{aiCandidate.slogan}</p><p><span>副标题</span>{aiCandidate.subtitle}</p><small>点击“使用文案建议”即可应用。</small></div>}
    <section className="ead-visual-preferences"><div className="ead-session-heading"><div><b>主视觉偏好</b><small>只需选择想表达的方向；尺寸安全区、禁用文字和品牌风格由系统自动执行。</small></div></div><div className="ead-grid"><label className="ead-select"><span>体育项目</span><select value={form.sportType} onChange={(event) => onField("sportType", event.target.value as FormState["sportType"])}><option value="auto">自动识别</option><option value="tennis">网球</option><option value="badminton">羽毛球</option><option value="basketball">篮球</option><option value="football">足球</option><option value="volleyball">排球</option><option value="table_tennis">乒乓球</option><option value="tug_of_war">拔河</option><option value="running">跑步 / 田径</option><option value="other">其他体育赛事</option></select></label><label className="ead-select"><span>主题色</span><select value={form.themeColor} onChange={(event) => onField("themeColor", event.target.value as FormState["themeColor"])}><option value="auto">自动</option><option value="blue">蓝色</option><option value="green">绿色</option><option value="red">红色</option><option value="yellow">黄色</option><option value="purple">紫色</option><option value="orange">橙色</option><option value="neutral">黑白中性色</option></select></label><label className="ead-select"><span>人物</span><select value={form.peopleMode} onChange={(event) => onField("peopleMode", event.target.value as FormState["peopleMode"])}><option value="auto">自动</option><option value="forbid">不出现人物</option><option value="allow">允许人物局部</option></select></label><label className="ead-select"><span>视觉类型</span><select value={form.visualType} onChange={(event) => onField("visualType", event.target.value as FormState["visualType"])}><option value="auto">自动</option><option value="action">动作瞬间</option><option value="equipment">器材特写</option><option value="venue">场地空间</option></select></label><Field className="ead-span-2" label="视觉表现（选填）" value={form.visualTreatment} maxLength={80} hint="如：极低机位、强透视、运动模糊、场地空间" onChange={(value) => onField("visualTreatment", value)} /></div>{form.sportType === "other" && <label className="ead-sport-confirm"><input type="checkbox" checked={form.sportsConfirmed} onChange={(event) => onField("sportsConfirmed", event.target.checked)} />确认这是体育赛事；非体育活动请改用对应场景。</label>}</section>
    <div className="ead-session-block"><div className="ead-session-heading"><b>活动信息</b></div><div className="ead-grid"><Field label="01 比赛日期" required={!form.renderTargets.every((target) => target === "banner_2227x950")} type="date" value={form.session.date} onChange={(value) => onSession("date", value)} /><Field label="02 比赛地点" required={!form.renderTargets.every((target) => target === "banner_2227x950")} value={form.session.location} onChange={(value) => onSession("location", value)} /><Field className="ead-span-2" label="03 参与对象" required={!form.renderTargets.every((target) => target === "banner_2227x950")} value={form.audience} onChange={(value) => onField("audience", value)} /><TextField className="ead-span-2" label="04 赛事规则" value={form.rules} onChange={(value) => onField("rules", value)} /></div></div>
    {form.renderTargets.includes("longform_1080xAuto") && <section className="ead-finalists"><div className="ead-session-heading"><div><b>决赛名单</b><small>固定 5 个组别；每组 1–6 人，将按实际人数自动展开长图。</small></div></div>{form.finalistGroups.map((group, groupIndex) => <div className="ead-finalist-group" key={group.label}><header><b>{group.label}</b><small>{group.entrants.length} / 6 人</small></header><div className="ead-finalist-entries">{group.entrants.map((entrant, entrantIndex) => <div className="ead-finalist-entry" key={`${group.label}-${entrantIndex}`}><input aria-label={`${group.label}第${entrantIndex + 1}人姓名`} placeholder="姓名" value={entrant.name} onChange={(event) => onField("finalistGroups", form.finalistGroups.map((item, index) => index === groupIndex ? { ...item, entrants: item.entrants.map((person, personIndex) => personIndex === entrantIndex ? { ...person, name: event.target.value } : person) } : item))} /><input aria-label={`${group.label}第${entrantIndex + 1}人赛区`} placeholder="所属赛区" value={entrant.region} onChange={(event) => onField("finalistGroups", form.finalistGroups.map((item, index) => index === groupIndex ? { ...item, entrants: item.entrants.map((person, personIndex) => personIndex === entrantIndex ? { ...person, region: event.target.value } : person) } : item))} /><button type="button" aria-label={`移除${group.label}第${entrantIndex + 1}人`} disabled={group.entrants.length <= 1} onClick={() => onField("finalistGroups", form.finalistGroups.map((item, index) => index === groupIndex ? { ...item, entrants: item.entrants.filter((_, personIndex) => personIndex !== entrantIndex) } : item))}>移除</button></div>)}</div><button type="button" className="ead-add-finalist" disabled={group.entrants.length >= 6} onClick={() => onField("finalistGroups", form.finalistGroups.map((item, index) => index === groupIndex ? { ...item, entrants: [...item.entrants, { name: "", region: "" }] } : item))}>＋ 添加名单</button></div>)}</section>}
    <div className="ead-qr-subsection"><div className="ead-qr-title"><b>二维码</b><small>{form.renderTargets.some((target) => target === "portrait_1080x1920" || target === "landscape_1920x1080") ? "竖版和横版生成前需提供：链接生成或上传图片二选一" : "选填：链接生成或上传图片二选一"}</small></div><div className="ead-qr-options"><button type="button" className={qrMode === "none" ? "is-selected" : ""} onClick={() => onQrMode("none")}>○ 不添加</button><button type="button" className={qrMode === "add" ? "is-selected" : ""} onClick={() => onQrMode("add")}>＋ 添加</button></div>{qrMode === "add" && <div className="ead-qr-add"><div className="ead-qr-add-grid"><input type="url" placeholder="粘贴报名 URL（会生成二维码）" value={form.qrUrl} onChange={(event) => onQrUrl(event.target.value)} /><label className="ead-upload-label">{qrUploadPending ? "正在上传…" : "上传二维码图片"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={qrUploadPending} onChange={(event) => { onQrUpload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label></div><div className="ead-upload-status"><span>{qrUploadPending ? "正在安全校验并保存二维码图片…" : form.qrAssetId ? `已上传：${form.qrAssetName}（将进入最终海报）` : form.qrUrl ? "URL 将用于服务端生成二维码" : "支持 PNG / JPEG / WebP，最大 5MB，最小 96 × 96 像素"}</span>{form.qrAssetId && <button type="button" onClick={onClearQrAsset}>移除图片</button>}</div></div>}</div>
  </section><button type="submit" className="ead-primary" disabled={pending || qrUploadPending}>{pending ? "正在处理…" : "确认文案，进入主视觉 →"}</button></form>;
}
