"use client";
import type { FormEvent } from "react";
import { t01PortraitSubtitleRecommendedCharacters, t01PortraitTitleRecommendedCharacters } from "@/contracts/poster";
import { Field, SectionHead, TextField } from "../fields";
import type { FormState, QrMode, SessionState } from "../types";
import type { RenderTargetId } from "@/contracts/brand";

const targets: Array<[RenderTargetId, string, string]> = [["portrait_1080x1920", "竖版", "1080 × 1920"], ["landscape_1920x1080", "横版", "1920 × 1080"], ["banner_2227x950", "Banner", "2227 × 950"], ["longform_1080xAuto", "长图", "1080 × 自动"]];
type Props = { form: FormState; qrMode: QrMode; qrUploadPending: boolean; aiReady: boolean; aiCandidate?: { slogan: string; subtitle: string }; onToggleRenderTarget: (target: RenderTargetId) => void; onField: <K extends keyof FormState>(key: K, value: FormState[K]) => void; onQrUrl: (value: string) => void; onSession: (key: keyof SessionState, value: string) => void; onQrMode: (mode: QrMode) => void; onQrUpload: (file?: File) => void; onClearQrAsset: () => void; onAssist: () => void; onSubmit: (event: FormEvent) => void; pending: boolean };

export function StepOne({ form, qrMode, qrUploadPending, aiReady, aiCandidate, onToggleRenderTarget, onField, onQrUrl, onSession, onQrMode, onQrUpload, onClearQrAsset, onAssist, onSubmit, pending }: Props) {
  return <form onSubmit={onSubmit}><section className="ead-section"><SectionHead index="01" title="填写并确认文案" hint="编辑会立即同步到 T01 竖版预览" />
    <div className="ead-template-picker"><b>选择输出模板</b><small>可多选，至少保留一款；右侧切换仅改变预览。仅需 Banner 时，请取消其余模板。</small><div>{targets.map(([target, name, size]) => <button type="button" key={target} className={form.renderTargets.includes(target) ? "is-selected" : ""} onClick={() => onToggleRenderTarget(target)}><span>{form.renderTargets.includes(target) ? "✓" : "＋"}</span><strong>{name}</strong><small>{size}</small></button>)}</div></div>
    <div className="ead-grid"><Field className="ead-span-2" label="一级大标题" required value={form.activityName} hint={`宽度 952px、高度自适应；建议 ${t01PortraitTitleRecommendedCharacters} 字以内，AI 不会改写`} onChange={(value) => onField("activityName", value)} /><Field className="ead-span-2" label="宣言标题" required value={form.slogan} maxLength={40} hint="格式：九号员工活动名称 / ENGLISH；可手填或由 AI 生成" onChange={(value) => onField("slogan", value)} /><Field className="ead-span-2" label="副标题" required value={form.subtitle} maxLength={40} hint={`建议 ${t01PortraitSubtitleRecommendedCharacters} 字以内；可手填或由 AI 生成`} onChange={(value) => onField("subtitle", value)} /></div>
    <div className="ead-copy-actions"><button type="button" className="ead-secondary" onClick={onAssist} disabled={pending}>{pending ? "正在生成…" : aiReady ? "替换两个小标题" : "AI 辅助生成小标题"}</button><small>{aiReady ? "预览仍显示当前输入；确认替换后才会同步两个小标题。" : "仅辅助两个小标题，不会修改大标题或活动事实。"}</small></div>
    {aiReady && aiCandidate && <div className="ead-ai-candidate"><b>AI 候选文案</b><p><span>宣言标题</span>{aiCandidate.slogan}</p><p><span>副标题</span>{aiCandidate.subtitle}</p><small>点击“替换两个小标题”会立即应用到输入框与预览。</small></div>}
    <div className="ead-session-block"><div className="ead-session-heading"><b>活动信息</b><small>{form.renderTargets.every((target) => target === "banner_2227x950") ? "仅选 Banner 时可留空" : "竖版、横版或长图已选时必填"}</small></div><div className="ead-grid"><Field label="01 比赛日期" required={!form.renderTargets.every((target) => target === "banner_2227x950")} type="date" value={form.session.date} onChange={(value) => onSession("date", value)} /><Field label="02 比赛地点" required={!form.renderTargets.every((target) => target === "banner_2227x950")} value={form.session.location} onChange={(value) => onSession("location", value)} /><Field className="ead-span-2" label="03 参与对象" required={!form.renderTargets.every((target) => target === "banner_2227x950")} value={form.audience} onChange={(value) => onField("audience", value)} /><TextField className="ead-span-2" label="04 赛事规则" value={form.rules} onChange={(value) => onField("rules", value)} /></div></div>
    <div className="ead-qr-subsection"><div className="ead-qr-title"><b>二维码</b><small>选填：链接生成或上传图片二选一</small></div><div className="ead-qr-options"><button type="button" className={qrMode === "none" ? "is-selected" : ""} onClick={() => onQrMode("none")}>○ 不添加</button><button type="button" className={qrMode === "add" ? "is-selected" : ""} onClick={() => onQrMode("add")}>＋ 添加</button></div>{qrMode === "add" && <div className="ead-qr-add"><div className="ead-qr-add-grid"><input type="url" placeholder="粘贴报名 URL（会生成二维码）" value={form.qrUrl} onChange={(event) => onQrUrl(event.target.value)} /><label className="ead-upload-label">{qrUploadPending ? "正在上传…" : "上传二维码图片"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={qrUploadPending} onChange={(event) => { onQrUpload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label></div><div className="ead-upload-status"><span>{qrUploadPending ? "正在安全校验并保存二维码图片…" : form.qrAssetId ? `已上传：${form.qrAssetName}（将进入最终海报）` : form.qrUrl ? "URL 将用于服务端生成二维码" : "支持 PNG / JPEG / WebP，最大 5MB，最小 96 × 96 像素"}</span>{form.qrAssetId && <button type="button" onClick={onClearQrAsset}>移除图片</button>}</div></div>}</div>
  </section><button type="submit" className="ead-primary" disabled={pending || qrUploadPending}>{pending ? "正在处理…" : "确认文案，进入主视觉 →"}</button></form>;
}
