"use client";
import type { FormEvent } from "react";
import { t01PortraitTitleMaxCharacters, t01PortraitTitleRecommendedCharacters } from "@/contracts/poster";
import { Field, SectionHead, TextField } from "../fields";
import type { FormState, QrMode, SessionState } from "../types";

type Props = { form: FormState; qrMode: QrMode; qrUploadPending: boolean; onField: <K extends keyof FormState>(key: K, value: FormState[K]) => void; onQrUrl: (value: string) => void; onSession: (key: keyof SessionState, value: string) => void; onQrMode: (mode: QrMode) => void; onQrUpload: (file?: File) => void; onClearQrAsset: () => void; onSubmit: (event: FormEvent) => void; pending: boolean };

export function StepOne({ form, qrMode, qrUploadPending, onField, onQrUrl, onSession, onQrMode, onQrUpload, onClearQrAsset, onSubmit, pending }: Props) {
  return <form onSubmit={onSubmit}>
    <section className="ead-section"><SectionHead index="01" title="必填信息" hint="用于锁定活动事实，不由 AI 擅自修改" />
      <div className="ead-grid"><Field className="ead-span-2" label="主题" required value={form.activityName} maxLength={t01PortraitTitleMaxCharacters} hint={`一级标题宽度 952px、高度自适应；建议 ${t01PortraitTitleRecommendedCharacters} 字以内，最终按实际边界校验`} onChange={(value) => onField("activityName", value)} /><Field className="ead-span-2" label="参与对象" required value={form.audience} onChange={(value) => onField("audience", value)} /></div>
      <div className="ead-session-block"><div className="ead-session-heading"><b>活动安排</b></div><div className="ead-grid"><Field label="日期" required type="date" value={form.session.date} onChange={(value) => onSession("date", value)} /><Field label="时间" required value={form.session.time} onChange={(value) => onSession("time", value)} /><Field className="ead-span-2" label="地点" required value={form.session.location} onChange={(value) => onSession("location", value)} /></div></div>
    </section>
    <section className="ead-section"><SectionHead index="02" title="可选信息" hint="未填写的内容不会出现在海报上" /><div className="ead-grid"><TextField className="ead-span-2" label="补充说明" value={form.supplement} onChange={(value) => onField("supplement", value)} /><Field label="截止时间" value={form.deadline} onChange={(value) => onField("deadline", value)} /><Field label="联系人" value={form.contact} onChange={(value) => onField("contact", value)} /><TextField label="活动规则（长图可用空行分段、标题：正文）" value={form.rules} onChange={(value) => onField("rules", value)} /><TextField label="奖品" value={form.prize} onChange={(value) => onField("prize", value)} /></div>
      <div className="ead-qr-subsection"><div className="ead-qr-title"><b>二维码</b><small>链接生成或上传图片二选一</small></div><div className="ead-qr-options"><button type="button" className={qrMode === "none" ? "is-selected" : ""} onClick={() => onQrMode("none")}>○ 不添加</button><button type="button" className={qrMode === "add" ? "is-selected" : ""} onClick={() => onQrMode("add")}>＋ 添加</button></div>{qrMode === "add" && <div className="ead-qr-add"><div className="ead-qr-add-grid"><input type="url" placeholder="粘贴报名 URL（会生成二维码）" value={form.qrUrl} onChange={(event) => onQrUrl(event.target.value)} /><label className="ead-upload-label">{qrUploadPending ? "正在上传…" : "上传二维码图片"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={qrUploadPending} onChange={(event) => { onQrUpload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label></div><div className="ead-upload-status"><span>{qrUploadPending ? "正在安全校验并保存二维码图片…" : form.qrAssetId ? `已上传：${form.qrAssetName}（将进入最终海报）` : form.qrUrl ? "URL 将用于服务端生成二维码" : "支持 PNG / JPEG / WebP，最大 5MB，最小 96 × 96 像素"}</span>{form.qrAssetId && <button type="button" onClick={onClearQrAsset}>移除图片</button>}</div></div>}</div>
    </section>
    <button type="submit" className="ead-primary" disabled={pending || qrUploadPending}>{pending ? "正在提交…" : qrUploadPending ? "二维码图片上传中…" : "交给 AI 优化文案 →"}</button><p className="ead-submit-note">标题建议 {t01PortraitTitleRecommendedCharacters} 字以内；主题、日期、时间、地点和参与对象将在后续步骤保持不变。二维码链接或已上传图片会作为锁定事实进入最终海报。</p>
  </form>;
}
